import Header from '@/components/ui/header';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Provider from './provider';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'bg-background bg-gray-100 font-sans antialiased',
          inter.variable,
          'flex flex-col min-h-[100dvh]'
        )}
      >
        <Provider>
          <Header />
          <main className="flex-1">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
